# POMO
model_params:
   'embedding_dim': 128
   'encoder_layer_num': 6 
   'qkv_dim': 16 
   'head_num': 8 
   'logit_clipping': 10
   'ff_hidden_dim': 512 
   'ffd': 'siglu' 
   'norm_type': 'rms' 
   'use_sparse': 'topk'   # relu topk entmax15 sparsemax a-entmax False 


optimizer_params:
    'optimizer':
        'weight_decay': 1e-6
    'scheduler':
        'name': 'MultiStepLR'
        'milestones': [270, 295] # [8001,8051]
        'gamma': 0.1

trainer_params:
    'epochs': 300
    'train_step': 391 
    'model_save_interval': 1

env:
  generator_params:
    num_loc: 50 # will been reset in run.py based on args.n_size
    variant_preset: "all" #
  test_epoch: [50, 150]  # 25 50 test in these epochs
  test_interval: 100 #
  test_episodes: 1000 
  test_batch_size: 200 # will be reset in env.py, function get_dataloader 
  data_dir: '../data/synthetic_data'
  test_size_idx: [ # will be reset in run.py based on args.n_size ??? why, have been delete
      0, # 50
      # 1, # 100
      # 2, # 200
      # 3  # 300
  ]
  test_problem_idx: [
   0, # "cvrp"
   1, # "ovrp",
   2, # "vrpb"
   3, # "vrpl"
   4, # "vrptw"
   5, # "ovrptw"
   6, # "ovrpb"
   7, #  "ovrpl"
   8, # "vrpbl"
   9, # "vrpbtw"
   10, # "vrpltw"
   11, # "ovrpbl"
   12, # "ovrpbtw"
   13, # "ovrpltw"
   14, # "vrpbltw"
   15  # "ovrpbltw"
  ]
  test_distribution_idx: [
  #   0, # "explosion"
  #   1, # "implosion"
  #   #2, # "cluster"
  #  3, # "rotation",
  #   4, # "linearprojection",
  #   #5, # "axisprojection",
  #   6, # "expansion",
  #   #7, # "compression",
  #   8 # "grid",
    9 # "uniform",
  ]
##################################################################################################
metric_label: [
  '0l/0loss', 
  '1c/0cost',  
  '3grad/0g',]

test_metric_label: [ # will be re set in run.py
    '1g/0gap',
    '2ag/0aug_gap',
]

all_test_size: [50, 100, 200, 300]

all_test_problem: [
  "cvrp",
  "ovrp",
  "vrpb",
  "vrpbl",
  "vrpbtw",
  "ovrpb",
  "ovrpbltw",
  "ovrpl",
  "vrptw",
  "vrpl",
  "ovrptw",  
  "vrpbltw",
  "vrpltw",
  "ovrpbl",
  "ovrpbtw",
  "ovrpltw",
]

all_test_distribution : [
  "explosion",
  "implosion",
  "cluster",
  "rotation",
  "linearprojection",
  "axisprojection",
  "expansion",
  "compression",
  "grid",
  "uniform"

]
